package me.wluo.imhere.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.wluo.imhere.pojo.SatelliteInfo;

import me.wluo.imhere.db.SatelliteInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig satelliteInfoDaoConfig;

    private final SatelliteInfoDao satelliteInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        satelliteInfoDaoConfig = daoConfigMap.get(SatelliteInfoDao.class).clone();
        satelliteInfoDaoConfig.initIdentityScope(type);

        satelliteInfoDao = new SatelliteInfoDao(satelliteInfoDaoConfig, this);

        registerDao(SatelliteInfo.class, satelliteInfoDao);
    }
    
    public void clear() {
        satelliteInfoDaoConfig.clearIdentityScope();
    }

    public SatelliteInfoDao getSatelliteInfoDao() {
        return satelliteInfoDao;
    }

}
